//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServiceTests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edu.softserve.com/", ConfigurationName="ServiceReference1.CalcSEI")]
    public interface CalcSEI {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.modResponse mod(SOAPServiceTests.ServiceReference1.mod request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mod", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.modResponse> modAsync(SOAPServiceTests.ServiceReference1.mod request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.addResponse add(SOAPServiceTests.ServiceReference1.add request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Add", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.addResponse> addAsync(SOAPServiceTests.ServiceReference1.add request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.divResponse div(SOAPServiceTests.ServiceReference1.div request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.divResponse> divAsync(SOAPServiceTests.ServiceReference1.div request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.subResponse sub(SOAPServiceTests.ServiceReference1.sub request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.subResponse> subAsync(SOAPServiceTests.ServiceReference1.sub request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.factorialResponse factorial(SOAPServiceTests.ServiceReference1.factorial request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Factorial", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.factorialResponse> factorialAsync(SOAPServiceTests.ServiceReference1.factorial request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.mulResponse mul(SOAPServiceTests.ServiceReference1.mul request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.mulResponse> mulAsync(SOAPServiceTests.ServiceReference1.mul request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.sqrResponse sqr(SOAPServiceTests.ServiceReference1.sqr request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqr", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.sqrResponse> sqrAsync(SOAPServiceTests.ServiceReference1.sqr request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.sqrtResponse sqrt(SOAPServiceTests.ServiceReference1.sqrt request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Sqrt", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.sqrtResponse> sqrtAsync(SOAPServiceTests.ServiceReference1.sqrt request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        SOAPServiceTests.ServiceReference1.aboutResponse about(SOAPServiceTests.ServiceReference1.about request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:About", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.aboutResponse> aboutAsync(SOAPServiceTests.ServiceReference1.about request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOAPServiceTests.ServiceReference1.powResponse pow(SOAPServiceTests.ServiceReference1.pow request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Pow", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.powResponse> powAsync(SOAPServiceTests.ServiceReference1.pow request);
        
        // CODEGEN: Generating message contract since the wrapper name (divResponse1) of message div1Response does not match the default value (div1)
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        SOAPServiceTests.ServiceReference1.div1Response div1(SOAPServiceTests.ServiceReference1.div1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Div1", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.div1Response> div1Async(SOAPServiceTests.ServiceReference1.div1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mod", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mod {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public mod() {
        }
        
        public mod(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class modResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public modResponse() {
        }
        
        public modResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class add {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public add() {
        }
        
        public add(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public addResponse() {
        }
        
        public addResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public div() {
        }
        
        public div(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divResponse() {
        }
        
        public divResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sub {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public sub() {
        }
        
        public sub(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public subResponse() {
        }
        
        public subResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorial", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorial {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        public factorial() {
        }
        
        public factorial(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="factorialResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class factorialResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public factorialResponse() {
        }
        
        public factorialResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mul {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public mul() {
        }
        
        public mul(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public mulResponse() {
        }
        
        public mulResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqr", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqr {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqr() {
        }
        
        public sqr(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrResponse() {
        }
        
        public sqrResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrt", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrt {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        public sqrt() {
        }
        
        public sqrt(double arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sqrtResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class sqrtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public sqrtResponse() {
        }
        
        public sqrtResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class about {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="about", Namespace="http://edu.softserve.com/", Order=0)]
        public SOAPServiceTests.ServiceReference1.aboutBody Body;
        
        public about() {
        }
        
        public about(SOAPServiceTests.ServiceReference1.aboutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public aboutBody() {
        }
        
        public aboutBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aboutResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public SOAPServiceTests.ServiceReference1.aboutResponseBody Body;
        
        public aboutResponse() {
        }
        
        public aboutResponse(SOAPServiceTests.ServiceReference1.aboutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class aboutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public aboutResponseBody() {
        }
        
        public aboutResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class pow {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double arg1;
        
        public pow() {
        }
        
        public pow(double arg0, double arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public powResponse() {
        }
        
        public powResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public div1() {
        }
        
        public div1(int arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse1", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class div1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public div1Response() {
        }
        
        public div1Response(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalcSEIChannel : SOAPServiceTests.ServiceReference1.CalcSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalcSEIClient : System.ServiceModel.ClientBase<SOAPServiceTests.ServiceReference1.CalcSEI>, SOAPServiceTests.ServiceReference1.CalcSEI {
        
        public CalcSEIClient() {
        }
        
        public CalcSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalcSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.modResponse SOAPServiceTests.ServiceReference1.CalcSEI.mod(SOAPServiceTests.ServiceReference1.mod request) {
            return base.Channel.mod(request);
        }
        
        public int mod(int arg0, int arg1) {
            SOAPServiceTests.ServiceReference1.mod inValue = new SOAPServiceTests.ServiceReference1.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.modResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).mod(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.modResponse> SOAPServiceTests.ServiceReference1.CalcSEI.modAsync(SOAPServiceTests.ServiceReference1.mod request) {
            return base.Channel.modAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.modResponse> modAsync(int arg0, int arg1) {
            SOAPServiceTests.ServiceReference1.mod inValue = new SOAPServiceTests.ServiceReference1.mod();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).modAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.addResponse SOAPServiceTests.ServiceReference1.CalcSEI.add(SOAPServiceTests.ServiceReference1.add request) {
            return base.Channel.add(request);
        }
        
        public double add(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.add inValue = new SOAPServiceTests.ServiceReference1.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.addResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.addResponse> SOAPServiceTests.ServiceReference1.CalcSEI.addAsync(SOAPServiceTests.ServiceReference1.add request) {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.addResponse> addAsync(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.add inValue = new SOAPServiceTests.ServiceReference1.add();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.divResponse SOAPServiceTests.ServiceReference1.CalcSEI.div(SOAPServiceTests.ServiceReference1.div request) {
            return base.Channel.div(request);
        }
        
        public double div(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.div inValue = new SOAPServiceTests.ServiceReference1.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.divResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).div(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.divResponse> SOAPServiceTests.ServiceReference1.CalcSEI.divAsync(SOAPServiceTests.ServiceReference1.div request) {
            return base.Channel.divAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.divResponse> divAsync(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.div inValue = new SOAPServiceTests.ServiceReference1.div();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).divAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.subResponse SOAPServiceTests.ServiceReference1.CalcSEI.sub(SOAPServiceTests.ServiceReference1.sub request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.sub inValue = new SOAPServiceTests.ServiceReference1.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.subResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).sub(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.subResponse> SOAPServiceTests.ServiceReference1.CalcSEI.subAsync(SOAPServiceTests.ServiceReference1.sub request) {
            return base.Channel.subAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.subResponse> subAsync(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.sub inValue = new SOAPServiceTests.ServiceReference1.sub();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).subAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.factorialResponse SOAPServiceTests.ServiceReference1.CalcSEI.factorial(SOAPServiceTests.ServiceReference1.factorial request) {
            return base.Channel.factorial(request);
        }
        
        public long factorial(int arg0) {
            SOAPServiceTests.ServiceReference1.factorial inValue = new SOAPServiceTests.ServiceReference1.factorial();
            inValue.arg0 = arg0;
            SOAPServiceTests.ServiceReference1.factorialResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).factorial(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.factorialResponse> SOAPServiceTests.ServiceReference1.CalcSEI.factorialAsync(SOAPServiceTests.ServiceReference1.factorial request) {
            return base.Channel.factorialAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.factorialResponse> factorialAsync(int arg0) {
            SOAPServiceTests.ServiceReference1.factorial inValue = new SOAPServiceTests.ServiceReference1.factorial();
            inValue.arg0 = arg0;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).factorialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.mulResponse SOAPServiceTests.ServiceReference1.CalcSEI.mul(SOAPServiceTests.ServiceReference1.mul request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.mul inValue = new SOAPServiceTests.ServiceReference1.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.mulResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).mul(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.mulResponse> SOAPServiceTests.ServiceReference1.CalcSEI.mulAsync(SOAPServiceTests.ServiceReference1.mul request) {
            return base.Channel.mulAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.mulResponse> mulAsync(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.mul inValue = new SOAPServiceTests.ServiceReference1.mul();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).mulAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.sqrResponse SOAPServiceTests.ServiceReference1.CalcSEI.sqr(SOAPServiceTests.ServiceReference1.sqr request) {
            return base.Channel.sqr(request);
        }
        
        public double sqr(double arg0) {
            SOAPServiceTests.ServiceReference1.sqr inValue = new SOAPServiceTests.ServiceReference1.sqr();
            inValue.arg0 = arg0;
            SOAPServiceTests.ServiceReference1.sqrResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).sqr(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.sqrResponse> SOAPServiceTests.ServiceReference1.CalcSEI.sqrAsync(SOAPServiceTests.ServiceReference1.sqr request) {
            return base.Channel.sqrAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.sqrResponse> sqrAsync(double arg0) {
            SOAPServiceTests.ServiceReference1.sqr inValue = new SOAPServiceTests.ServiceReference1.sqr();
            inValue.arg0 = arg0;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).sqrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.sqrtResponse SOAPServiceTests.ServiceReference1.CalcSEI.sqrt(SOAPServiceTests.ServiceReference1.sqrt request) {
            return base.Channel.sqrt(request);
        }
        
        public double sqrt(double arg0) {
            SOAPServiceTests.ServiceReference1.sqrt inValue = new SOAPServiceTests.ServiceReference1.sqrt();
            inValue.arg0 = arg0;
            SOAPServiceTests.ServiceReference1.sqrtResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).sqrt(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.sqrtResponse> SOAPServiceTests.ServiceReference1.CalcSEI.sqrtAsync(SOAPServiceTests.ServiceReference1.sqrt request) {
            return base.Channel.sqrtAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.sqrtResponse> sqrtAsync(double arg0) {
            SOAPServiceTests.ServiceReference1.sqrt inValue = new SOAPServiceTests.ServiceReference1.sqrt();
            inValue.arg0 = arg0;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).sqrtAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.aboutResponse SOAPServiceTests.ServiceReference1.CalcSEI.about(SOAPServiceTests.ServiceReference1.about request) {
            return base.Channel.about(request);
        }
        
        public string about(string arg0) {
            SOAPServiceTests.ServiceReference1.about inValue = new SOAPServiceTests.ServiceReference1.about();
            inValue.Body = new SOAPServiceTests.ServiceReference1.aboutBody();
            inValue.Body.arg0 = arg0;
            SOAPServiceTests.ServiceReference1.aboutResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).about(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.aboutResponse> SOAPServiceTests.ServiceReference1.CalcSEI.aboutAsync(SOAPServiceTests.ServiceReference1.about request) {
            return base.Channel.aboutAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.aboutResponse> aboutAsync(string arg0) {
            SOAPServiceTests.ServiceReference1.about inValue = new SOAPServiceTests.ServiceReference1.about();
            inValue.Body = new SOAPServiceTests.ServiceReference1.aboutBody();
            inValue.Body.arg0 = arg0;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).aboutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.powResponse SOAPServiceTests.ServiceReference1.CalcSEI.pow(SOAPServiceTests.ServiceReference1.pow request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.pow inValue = new SOAPServiceTests.ServiceReference1.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.powResponse retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).pow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.powResponse> SOAPServiceTests.ServiceReference1.CalcSEI.powAsync(SOAPServiceTests.ServiceReference1.pow request) {
            return base.Channel.powAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.powResponse> powAsync(double arg0, double arg1) {
            SOAPServiceTests.ServiceReference1.pow inValue = new SOAPServiceTests.ServiceReference1.pow();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).powAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServiceTests.ServiceReference1.div1Response SOAPServiceTests.ServiceReference1.CalcSEI.div1(SOAPServiceTests.ServiceReference1.div1 request) {
            return base.Channel.div1(request);
        }
        
        public int div1(int arg0, int arg1) {
            SOAPServiceTests.ServiceReference1.div1 inValue = new SOAPServiceTests.ServiceReference1.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            SOAPServiceTests.ServiceReference1.div1Response retVal = ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).div1(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.div1Response> SOAPServiceTests.ServiceReference1.CalcSEI.div1Async(SOAPServiceTests.ServiceReference1.div1 request) {
            return base.Channel.div1Async(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServiceTests.ServiceReference1.div1Response> div1Async(int arg0, int arg1) {
            SOAPServiceTests.ServiceReference1.div1 inValue = new SOAPServiceTests.ServiceReference1.div1();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((SOAPServiceTests.ServiceReference1.CalcSEI)(this)).div1Async(inValue);
        }
    }
}
